# SPDX-FileCopyrightText: Copyright 2024 Prasad Tengse
# SPDX-License-Identifier: MIT
builds:
  - id: default
    flags:
      - -trimpath
      - -tags
      - netgo,osusergo
    ldflags:
      - -s -w
