name: test
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          # - "1.22rc2"
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Test
        run: task test
        env:
          CGO_ENABLED: "0"

      - name: Coverage Create Profile
        # Do not use '-{flag}={arg}' format if arg contains dot '.', or single dashes '-'
        # for flag with dot '.' (like test.v) as PowerShell mangles it.
        # See https://github.com/PowerShell/PowerShell/issues/6291#issuecomment-747104988 for more context.
        run: go tool covdata textfmt -i .gocover -o .gocover/coverage.out

      - name: Coverage View Profile
        # Do not use '-{flag}={arg}' format if arg contains dot '.', or single dashes '-'
        # for flag with dot '.' (like test.v) as PowerShell mangles it.
        # See https://github.com/PowerShell/PowerShell/issues/6291#issuecomment-747104988 for more context.
        run: go tool cover -func .gocover/coverage.out
